include:
  - board: ergodash_mini_central_dongle
    snippet: studio-rpc-usb-uart
    artifact-name: ergodash_mini_central_dongle
  
  - board: ergodash_mini_central_left
    artifact-name: ergodash_mini_central_left
    
  - board: ergodash_mini_peripheral_left
    snippet: studio-rpc-usb-uart
    artifact-name: ergodash_mini_peripheral_left
    
  - board: ergodash_mini_peripheral_right
    artifact-name: ergodash_mini_peripheral_right
    
  - board: nice_nano_v2
    shield: settings_reset
